test: enable console log checks
ng-bootstrap/ng-bootstrap pull request #4016
Opened 2021-02-22 15:35 UTC by fbasso

2021-02-24 13:09 UTC, maxokorokov requested changes
Hey, @fbasso,

- I think we should turn off all reporting that causes issues instead of filtering it out in the code
- Also maybe we should look only for warnings and errors

2021-02-24 13:09 UTC, maxokorokov commented on e2e-app/setup.pw-spec.ts
> +      if (message.includes('Angular is running') || message.includes('Live Reloading')) {
We should simply turn off live reloading for tests, like it is done for the demo for example:
- run demo with a specific config for playwright `yarn e2e-app:serve -c playwright`
- similar to https://github.com/ng-bootstrap/ng-bootstrap/blob/master/angular.json#L155-L158

I guess it should be something like:

```
"playwright": {
  "browserTarget": "demo:build:production",
  "liveReload": false,
  "watch": false,
  "extractLicenses": false
}
```

2021-02-24 13:09 UTC, maxokorokov commented on e2e-app/setup.pw-spec.ts
> +    const consoleMsgs: Array<string> = ['Unexpected console messages found'];
I think `Array<string>` is redundant here

2021-02-26 13:12 UTC, fbasso commented
Thanks for the review @maxokorokov !

I did the changes. I also listen for the 'pageerror' event (uncaught exceptions), which normally don't happen (every thing seems to be caught at the higher level) , but just in case, it good to report too.

2021-02-26 13:20 UTC, maxokorokov reviewed
Hey, @fbasso !

Left some comments

2021-02-26 13:20 UTC, maxokorokov commented on package.json
> +    "ngb:e2e": "concurrently --success first --kill-others \"yarn e2e-app:serve --prod --no-watch -c playwright\" \"yarn ngb:e2e-playwright BROWSER=chromium && yarn ngb:e2e-playwright BROWSER=firefox
I think you can remove `--prod` and `--no-watch` and add 
`"browserTarget": "e2e-app:build:production"` in the `angular.json` configuration

2021-02-26 13:20 UTC, maxokorokov commented on e2e-app/setup.e2e-spec.ts
> +  test.page.on('console', async msg => {
type would be helpfull→ `(msg: ConsoleMessage)`

2021-02-26 13:20 UTC, maxokorokov commented on e2e-app/setup.e2e-spec.ts
> +      const length = msg.args().length;
maybe 

```ts
for (let m of msg.args()) {
  output.push(await m.jsonValue());
}
```

2021-02-26 13:20 UTC, maxokorokov commented on angular.json
> +              "liveReload": false,
what about the flag about extracting licenses?

2021-03-01 15:52 UTC, maxokorokov approved these changes
LGTM!

2021-03-01 15:52 UTC, merged