feat(positionning): open popperOptions api
ng-bootstrap/ng-bootstrap pull request #4323
Opened 2022-05-04 13:33 UTC by fbasso

2022-08-02 08:29 UTC, maxokorokov requested changes
Hey, left some comments!

2022-08-02 08:29 UTC, maxokorokov commented on src/datepicker/datepicker-input-config.ts
> +  popperOptions: (options: Partial<Options>) => Partial<Options>;
maybe we should initialize directly with function, not undefined?

2022-08-02 08:29 UTC, maxokorokov commented on src/datepicker/datepicker-input.ts
> +    this.popperOptions = config.popperOptions || ((options: Partial<Options>) => options);
if we initialize directly in config, we should avoid having this

2022-08-02 08:29 UTC, maxokorokov commented on src/datepicker/datepicker-input.ts
> +            updatePopperOptions: (options) => {
nitpick: arrow function?

2022-08-02 08:29 UTC, maxokorokov commented on src/util/positioning.spec.ts
> -      if (bsClass !== getBootstrapBaseClassPlacement('', popperClass as PopperPlacement)) {
👍

2022-08-02 08:29 UTC, maxokorokov commented on src/popover/popover.spec.ts
> +      popover.popperOptions = (options: Partial<Options>) => {
I wonder if we should explain how to use if more clearly in docs:
- is the initial config readonly or can be modified?
- should the user clone it?
- will initial config be discarded and ignored?

2022-08-02 09:32 UTC, fbasso commented
Thanks for your review and comments, @maxokorokov !

I've changed the code accordingly.

2022-08-02 13:51 UTC, maxokorokov approved these changes
LGTM!

2022-08-02 13:56 UTC, merged

2022-10-05 21:54 UTC, sergeyglazyrindev commented
Hello guys. Could you please suggest how do I proceed to get it working in my project ? The fix is not published yet on npm, right ? So, shall I use packag directly from github ? When are you gonna publish this version on npm ?