fix(positionning): fix start/end placements for popper
ng-bootstrap/ng-bootstrap pull request #4336
Opened 2022-05-30 13:49 UTC by fbasso

The purpose is to have the right placement for widgets using popper when the dir="rtl" is set on the html tag

2022-08-02 14:20 UTC, maxokorokov reviewed
I left 2 comments, could you please rebase and I'll review again :)

2022-08-03 13:13 UTC, maxokorokov requested changes
Hey,

left another review, please see inline comments.

Big things:
1. you shouldn't provide anything special in any of the tests, so `NgbTestRTL` and `NgbTestLTR` are not needed
2. integration tests are missing, meaning we don't have tests that say that "if we have a correct RTL attribute on <html> element, placement classes are correctly generated". Well, at least one test :)
3. We don't need `getLang()` at the moment, so let's remove it

Cheers,
Max

2022-08-03 13:13 UTC, maxokorokov commented on src/test/ngb-rtl.ts
> +export class NgbTestRTL {
This is used nowhere

2022-08-03 13:13 UTC, maxokorokov commented on src/test/ngb-rtl.ts
> +export class NgbTestLTR {
If you remove all `provides` from tests, this will not be used anywhere either

2022-08-03 13:22 UTC, fbasso commented
Thanks for your review @maxokorokov, I'm going to see the changes to be done.

2022-08-11 12:28 UTC, merged