feat(offcanvas): add static backdrop option
ng-bootstrap/ng-bootstrap pull request #4367
Opened 2022-07-29 09:28 UTC by jnizet

this aligns with Bootstrap 5.2.0 functionality

Before submitting a pull request, please make sure you have at least performed the following:

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md) and [DEVELOPER.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/DEVELOPER.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated any applicable tests.
 - [x] added/updated any applicable API documentation.
 - [x] added/updated any applicable demos.

2022-08-02 14:08 UTC, maxokorokov requested changes
Hey, @jnizet!
LGTM apart from small API typing issue in the `NgbOffcanvasConfig`

2022-08-02 14:08 UTC, maxokorokov commented on src/offcanvas/offcanvas-config.ts
> +  backdrop?: boolean | 'static';
You should type `backdrop: boolean | 'static' = true` in `NgbOffcanvasConfig` too (below in this file).
At the moment it is `backdrop = true` and typescript is unhappy when one tries to set it to 'static':

![Screenshot 2022-08-02 at 16 01 26](https://user-images.githubusercontent.com/8074436/182394077-e277f85e-9188-4859-9f63-a69fa071a9d3.jpg)

2022-08-02 18:31 UTC, jnizet commented
Good catch again @maxokorokov. Fixed.

2022-08-03 12:51 UTC, maxokorokov approved these changes
LGTM, thanks!

2022-08-03 12:52 UTC, merged