Bootstrap 5.3 and dark mode
ng-bootstrap/ng-bootstrap pull request #4554
Opened 2023-08-21 08:46 UTC by fbasso

Rebase of #4451 + some other fixes

2023-08-24 13:32 UTC, bastienmoulia requested changes
Thanks for taking this issue, I have some small suggestions to improve the documentation in dark mode.

2023-08-24 13:32 UTC, bastienmoulia commented on demo/src/app/shared/component-wrapper/component-wrapper.component.html
You can replace `style="border-right: 1px solid rgba(0, 0, 0, 0.1)"` by the class `border-end` to show the border in dark mode.

2023-08-24 13:32 UTC, bastienmoulia commented on demo/src/app/shared/page-wrapper/page-wrapper.component.html
You can replace `style="border-right: 1px solid rgba(0, 0, 0, 0.1)"` by the class `border-end` to show the border in dark mode.

2023-08-24 13:32 UTC, bastienmoulia commented on demo/src/style/app.scss
You can replace `color: rgba(0, 0, 0, 0.85);` by `color: rgba(var(--bs-emphasis-color-rgb), 0.85);`

2023-08-28 14:52 UTC, fbasso commented
Thanks for your help @bastienmoulia !

All your suggestions are valid, I have integrated them. The PR should be ready to be merge soon I think.

2023-10-23 13:28 UTC, bastienmoulia commented
Do you need some help to finish it?

2023-10-25 13:44 UTC, merged